---
# main.yaml

- hosts: all

  remote_user: pi
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - include: tasks/system.yaml
      tags:
        - system

    - include: tasks/3pp.yaml
      tags:
        - 3pp

    - include: tasks/app.yaml
      tags:
        - app

    - include: tasks/nginx.yaml
      tags:
        - nginx

  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted

    - name: Reload sysctl config
      command: sysctl -p

    - name: Restart fail2ban
      service: name=fail2ban state=restarted

    - name: Restart sshd
      service: name=ssh state=restarted

    - name: Restart unattended-upgrades
      service: name=unattended=upgrades state=restarted